version: 2
jobs:
  dep:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/tetafro/nott-backend-go
    steps:
      - checkout
      - run:
          name: Get project dependencies
          command: go mod download
      - save_cache:
          key: gomod-cache-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
  test:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/tetafro/nott-backend-go
    steps:
      - checkout
      - restore_cache:
          keys:
            - gomod-cache-{{ checksum "go.sum" }}
      - run:
          name: Run tests
          command: go test ./...
  lint:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/tetafro/nott-backend-go
    steps:
      - checkout
      - restore_cache:
          keys:
            - gomod-cache-{{ checksum "go.sum" }}
      - run:
          name: Install linters
          command: go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
      - run:
          name: Run linters
          command: golangci-lint run
  codecov:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/tetafro/nott-backend-go
    steps:
      - checkout
      - restore_cache:
          keys:
            - gomod-cache-{{ checksum "go.sum" }}
      - run: ./.circleci/codecov.sh
      - run: bash <(curl -s https://codecov.io/bash)
  publish:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/tetafro/nott-backend-go
    steps:
      - checkout
      - restore_cache:
          keys:
            - gomod-cache-{{ checksum "go.sum" }}
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: docker build -t tetafro/nott-backend-go .
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push tetafro/nott-backend-go:latest
workflows:
  version: 2
  main:
    jobs:
      - dep
      - test:
          requires:
            - dep
      - lint:
          requires:
            - dep
      - codecov:
          requires:
            - dep
            - test
      - publish:
          requires:
            - dep
            - test
            - lint
          context: dockerhub
